name: My First Action

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: prime-cache-252336a
        run: echo "Cache primed"

      - name: 24f1001527@ds.study.iitm.ac.in
        run: echo "Hello world"
